
name: GitHub Actions CI
on: [push]
jobs:
  First-Test-CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
  
  Python-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
            python-version: "3.x"
      - name: installing pip
        run: python3 -m pip install --upgrade pip
      - name: install pytest
        run: pip install PyTest
      - name: install NumPy
        run: pip install NumPy
      - name: install scipy
        run: pip install scipy
      - name: install pandas
        run: pip install pandas
      - name: install matplotlib
        run: pip install matplotlib
      - name: Run tests with pytest
        run: python3 -m pytest
